SECTION "Pics 1", ROMX

IF DEF(_SATURN)
AbraPicFront::        INCBIN "gfx/pokemon/front_saturn_1st_generation/063.pic"
AbraPicBack::         INCBIN "gfx/pokemon/back/abrab.pic"
AerodactylPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/142.pic"
AerodactylPicBack::   INCBIN "gfx/pokemon/back/aerodactylb.pic"
AipomPicFront::       INCBIN "gfx/pokemon/front_saturn_2nd_generation/190.pic"
AipomPicBack::        INCBIN "gfx/pokemon/back/aipomb.pic"
AlakazamPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/065.pic"
AlakazamPicBack::     INCBIN "gfx/pokemon/back/alakazamb.pic"
BellsproutPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/069.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/back/bellsproutb.pic"
BulbasaurPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/001.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/back/bulbasaurb.pic"
CaterpiePicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/010.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/back/caterpieb.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/004.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/back/charmanderb.pic"
ChikoritaPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/152.pic"
ChikoritaPicBack::    INCBIN "gfx/pokemon/back/chikoritab.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/035.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/back/clefairyb.pic"
CubonePicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/104.pic"
CubonePicBack::       INCBIN "gfx/pokemon/back/cuboneb.pic"
CyndaquilPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/155.pic"
CyndaquilPicBack::    INCBIN "gfx/pokemon/back/cyndaquilb.pic"
DiglettPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/050.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/back/diglettb.pic"
DittoPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/132.pic"
DittoPicBack::        INCBIN "gfx/pokemon/back/dittob.pic"
DoduoPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/084.pic"
DoduoPicBack::        INCBIN "gfx/pokemon/back/doduob.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/147.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/back/dratinib.pic"
ENDC
IF DEF(_MARS)
AbraPicFront::        INCBIN "gfx/pokemon/front_mars_1st_generation/063.pic"
AbraPicBack::         INCBIN "gfx/pokemon/back/abrab.pic"
AerodactylPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/142.pic"
AerodactylPicBack::   INCBIN "gfx/pokemon/back/aerodactylb.pic"
AipomPicFront::       INCBIN "gfx/pokemon/front_mars_2nd_generation/190.pic"
AipomPicBack::        INCBIN "gfx/pokemon/back/aipomb.pic"
AlakazamPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/065.pic"
AlakazamPicBack::     INCBIN "gfx/pokemon/back/alakazamb.pic"
BellsproutPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/069.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/back/bellsproutb.pic"
BulbasaurPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/001.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/back/bulbasaurb.pic"
CaterpiePicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/010.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/back/caterpieb.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/004.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/back/charmanderb.pic"
ChikoritaPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/152.pic"
ChikoritaPicBack::    INCBIN "gfx/pokemon/back/chikoritab.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/035.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/back/clefairyb.pic"
CubonePicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/104.pic"
CubonePicBack::       INCBIN "gfx/pokemon/back/cuboneb.pic"
CyndaquilPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/155.pic"
CyndaquilPicBack::    INCBIN "gfx/pokemon/back/cyndaquilb.pic"
DiglettPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/050.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/back/diglettb.pic"
DittoPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/132.pic"
DittoPicBack::        INCBIN "gfx/pokemon/back/dittob.pic"
DoduoPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/084.pic"
DoduoPicBack::        INCBIN "gfx/pokemon/back/doduob.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/147.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/back/dratinib.pic"
ENDC


SECTION "Pics 2", ROMX

IF DEF(_SATURN)
AmpharosPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/181.pic"
AmpharosPicBack::     INCBIN "gfx/pokemon/back/ampharosb.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/024.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/back/arbokb.pic"
EeveePicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/133.pic"
EeveePicBack::        INCBIN "gfx/pokemon/back/eeveeb.pic"
EkansPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/023.pic"
EkansPicBack::        INCBIN "gfx/pokemon/back/ekansb.pic"
ElectrodePicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/101.pic"
ElectrodePicBack::    INCBIN "gfx/pokemon/back/electrodeb.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/074.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/back/geodudeb.pic"
GrimerPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/088.pic"
GrimerPicBack::       INCBIN "gfx/pokemon/back/grimerb.pic"
GrowlithePicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/058.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/back/growlitheb.pic"
HoothootPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/163.pic"
HoothootPicBack::     INCBIN "gfx/pokemon/back/hoothootb.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/116.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/back/horseab.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/039.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/back/jigglypuffb.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/140.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/back/kabutob.pic"
KakunaPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/014.pic"
KakunaPicBack::       INCBIN "gfx/pokemon/back/kakunab.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/098.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/back/krabbyb.pic"
MachopPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/066.pic"
MachopPicBack::       INCBIN "gfx/pokemon/back/machopb.pic"
MagnemitePicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/081.pic"
MagnemitePicBack::    INCBIN "gfx/pokemon/back/magnemiteb.pic"
ENDC
IF DEF(_MARS)
AmpharosPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/181.pic"
AmpharosPicBack::     INCBIN "gfx/pokemon/back/ampharosb.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/024.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/back/arbokb.pic"
EeveePicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/133.pic"
EeveePicBack::        INCBIN "gfx/pokemon/back/eeveeb.pic"
EkansPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/023.pic"
EkansPicBack::        INCBIN "gfx/pokemon/back/ekansb.pic"
ElectrodePicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/101.pic"
ElectrodePicBack::    INCBIN "gfx/pokemon/back/electrodeb.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/074.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/back/geodudeb.pic"
GrimerPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/088.pic"
GrimerPicBack::       INCBIN "gfx/pokemon/back/grimerb.pic"
GrowlithePicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/058.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/back/growlitheb.pic"
HoothootPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/163.pic"
HoothootPicBack::     INCBIN "gfx/pokemon/back/hoothootb.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/116.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/back/horseab.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/039.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/back/jigglypuffb.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/140.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/back/kabutob.pic"
KakunaPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/014.pic"
KakunaPicBack::       INCBIN "gfx/pokemon/back/kakunab.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/098.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/back/krabbyb.pic"
MachopPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/066.pic"
MachopPicBack::       INCBIN "gfx/pokemon/back/machopb.pic"
MagnemitePicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/081.pic"
MagnemitePicBack::    INCBIN "gfx/pokemon/back/magnemiteb.pic"
ENDC


SECTION "Pics 3", ROMX

IF DEF(_SATURN)
ArcaninePicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/059.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/back/arcanineb.pic"
AriadosPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/168.pic"
AriadosPicBack::      INCBIN "gfx/pokemon/back/ariadosb.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/056.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/back/mankeyb.pic"
MareepPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/179.pic"
MareepPicBack::       INCBIN "gfx/pokemon/back/mareepb.pic"
MarillPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/183.pic"
MarillPicBack::       INCBIN "gfx/pokemon/back/marillb.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/052.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/back/meowthb.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/011.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/back/metapodb.pic"
MewPicFront::         INCBIN "gfx/pokemon/front_saturn_1st_generation/151.pic"
MewPicBack::          INCBIN "gfx/pokemon/back/mewb.pic"
NatuPicFront::        INCBIN "gfx/pokemon/front_saturn_2nd_generation/177.pic"
NatuPicBack::         INCBIN "gfx/pokemon/back/natub.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/029.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/back/nidoranfb.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/032.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/back/nidoranmb.pic"
OddishPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/043.pic"
OddishPicBack::       INCBIN "gfx/pokemon/back/oddishb.pic"
OmanytePicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/138.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/back/omanyteb.pic"
ParasPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/046.pic"
ParasPicBack::        INCBIN "gfx/pokemon/back/parasb.pic"
PhanpyPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/231.pic"
PhanpyPicBack::       INCBIN "gfx/pokemon/back/phanpyb.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/016.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/back/pidgeyb.pic"
ENDC
IF DEF(_MARS)
ArcaninePicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/059.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/back/arcanineb.pic"
AriadosPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/168.pic"
AriadosPicBack::      INCBIN "gfx/pokemon/back/ariadosb.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/056.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/back/mankeyb.pic"
MareepPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/179.pic"
MareepPicBack::       INCBIN "gfx/pokemon/back/mareepb.pic"
MarillPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/183.pic"
MarillPicBack::       INCBIN "gfx/pokemon/back/marillb.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/052.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/back/meowthb.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/011.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/back/metapodb.pic"
MewPicFront::         INCBIN "gfx/pokemon/front_mars_1st_generation/151.pic"
MewPicBack::          INCBIN "gfx/pokemon/back/mewb.pic"
NatuPicFront::        INCBIN "gfx/pokemon/front_mars_2nd_generation/177.pic"
NatuPicBack::         INCBIN "gfx/pokemon/back/natub.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/029.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/back/nidoranfb.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/032.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/back/nidoranmb.pic"
OddishPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/043.pic"
OddishPicBack::       INCBIN "gfx/pokemon/back/oddishb.pic"
OmanytePicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/138.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/back/omanyteb.pic"
ParasPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/046.pic"
ParasPicBack::        INCBIN "gfx/pokemon/back/parasb.pic"
PhanpyPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/231.pic"
PhanpyPicBack::       INCBIN "gfx/pokemon/back/phanpyb.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/016.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/back/pidgeyb.pic"
ENDC


SECTION "Pics 4", ROMX

RedPicBack::          INCBIN "gfx/player/redb.pic"
OldManPicBack::       INCBIN "gfx/battle/oldmanb.pic"
IF DEF(_SATURN)
ArticunoPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/144.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/back/articunob.pic"
AzumarillPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/184.pic"
AzumarillPicBack::    INCBIN "gfx/pokemon/back/azumarillb.pic"
BeedrillPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/015.pic"
BeedrillPicBack::     INCBIN "gfx/pokemon/back/beedrillb.pic"
BellossomPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/182.pic"
BellossomPicBack::    INCBIN "gfx/pokemon/back/bellossomb.pic"
BlastoisePicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/009.pic"
BlastoisePicBack::    INCBIN "gfx/pokemon/back/blastoiseb.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/012.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/back/butterfreeb.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/006.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/back/charizardb.pic"
CloysterPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/091.pic"
CloysterPicBack::     INCBIN "gfx/pokemon/back/cloysterb.pic"
CrobatPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/169.pic"
CrobatPicBack::       INCBIN "gfx/pokemon/back/crobatb.pic"
DodrioPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/085.pic"
DodrioPicBack::       INCBIN "gfx/pokemon/back/dodriob.pic"
ENDC
IF DEF(_MARS)
ArticunoPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/144.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/back/articunob.pic"
AzumarillPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/184.pic"
AzumarillPicBack::    INCBIN "gfx/pokemon/back/azumarillb.pic"
BeedrillPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/015.pic"
BeedrillPicBack::     INCBIN "gfx/pokemon/back/beedrillb.pic"
BellossomPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/182.pic"
BellossomPicBack::    INCBIN "gfx/pokemon/back/bellossomb.pic"
BlastoisePicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/009.pic"
BlastoisePicBack::    INCBIN "gfx/pokemon/back/blastoiseb.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/012.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/back/butterfreeb.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/006.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/back/charizardb.pic"
CloysterPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/091.pic"
CloysterPicBack::     INCBIN "gfx/pokemon/back/cloysterb.pic"
CrobatPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/169.pic"
CrobatPicBack::       INCBIN "gfx/pokemon/back/crobatb.pic"
DodrioPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/085.pic"
DodrioPicBack::       INCBIN "gfx/pokemon/back/dodriob.pic"
ENDC


SECTION "Pics 5", ROMX

IF DEF(_SATURN)
FossilKabutopsPic::   INCBIN "gfx/battle/fossilkabutops_saturn.pic"
FossilAerodactylPic:: INCBIN "gfx/battle/fossilaerodactyl_saturn.pic"
ENDC
IF DEF(_MARS)
FossilKabutopsPic::   INCBIN "gfx/battle/fossilkabutops_mars.pic"
FossilAerodactylPic:: INCBIN "gfx/battle/fossilaerodactyl_mars.pic"
ENDC
GhostPic::            INCBIN "gfx/battle/ghost.pic"
IF DEF(_SATURN)
DonphanPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/232.pic"
DonphanPicBack::      INCBIN "gfx/pokemon/back/donphanb.pic"
DragonitePicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/149.pic"
DragonitePicBack::    INCBIN "gfx/pokemon/back/dragoniteb.pic"
ExeggcutePicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/102.pic"
ExeggcutePicBack::    INCBIN "gfx/pokemon/back/exeggcuteb.pic"
ExeggutorPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/103.pic"
ExeggutorPicBack::    INCBIN "gfx/pokemon/back/exeggutorb.pic"
FearowPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/022.pic"
FearowPicBack::       INCBIN "gfx/pokemon/back/fearowb.pic"
GastlyPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/092.pic"
GastlyPicBack::       INCBIN "gfx/pokemon/back/gastlyb.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/042.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/back/golbatb.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/055.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/back/golduckb.pic"
GyaradosPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/130.pic"
GyaradosPicBack::     INCBIN "gfx/pokemon/back/gyaradosb.pic"
ENDC
IF DEF(_MARS)
DonphanPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/232.pic"
DonphanPicBack::      INCBIN "gfx/pokemon/back/donphanb.pic"
DragonitePicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/149.pic"
DragonitePicBack::    INCBIN "gfx/pokemon/back/dragoniteb.pic"
ExeggcutePicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/102.pic"
ExeggcutePicBack::    INCBIN "gfx/pokemon/back/exeggcuteb.pic"
ExeggutorPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/103.pic"
ExeggutorPicBack::    INCBIN "gfx/pokemon/back/exeggutorb.pic"
FearowPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/022.pic"
FearowPicBack::       INCBIN "gfx/pokemon/back/fearowb.pic"
GastlyPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/092.pic"
GastlyPicBack::       INCBIN "gfx/pokemon/back/gastlyb.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/042.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/back/golbatb.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/055.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/back/golduckb.pic"
GyaradosPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/130.pic"
GyaradosPicBack::     INCBIN "gfx/pokemon/back/gyaradosb.pic"
ENDC


SECTION "Pics 7", ROMX

IF DEF(_SATURN)
HitmonleePicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/106.pic"
HitmonleePicBack::    INCBIN "gfx/pokemon/back/hitmonleeb.pic"
HoohPicFront::        INCBIN "gfx/pokemon/front_saturn_2nd_generation/250.pic"
HoohPicBack::         INCBIN "gfx/pokemon/back/hoohb.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/025.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/back/pikachub.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/060.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/back/poliwagb.pic"
PsyduckPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/054.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/back/psyduckb.pic"
QwilfishPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/211.pic"
QwilfishPicBack::     INCBIN "gfx/pokemon/back/qwilfishb.pic"
RattataPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/019.pic"
RattataPicBack::      INCBIN "gfx/pokemon/back/rattatab.pic"
RemoraidPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/223.pic"
RemoraidPicBack::     INCBIN "gfx/pokemon/back/remoraidb.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/027.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/back/sandshrewb.pic"
ShellderPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/090.pic"
ShellderPicBack::     INCBIN "gfx/pokemon/back/shellderb.pic"
SlowpokePicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/079.pic"
SlowpokePicBack::     INCBIN "gfx/pokemon/back/slowpokeb.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/021.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/back/spearowb.pic"
SpinarakPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/167.pic"
SpinarakPicBack::     INCBIN "gfx/pokemon/back/spinarakb.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/007.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/back/squirtleb.pic"
TentacoolPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/072.pic"
TentacoolPicBack::    INCBIN "gfx/pokemon/back/tentacoolb.pic"
TogepiPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/175.pic"
TogepiPicBack::       INCBIN "gfx/pokemon/back/togepib.pic"
ENDC
IF DEF(_MARS)
HitmonleePicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/106.pic"
HitmonleePicBack::    INCBIN "gfx/pokemon/back/hitmonleeb.pic"
HoohPicFront::        INCBIN "gfx/pokemon/front_mars_2nd_generation/250.pic"
HoohPicBack::         INCBIN "gfx/pokemon/back/hoohb.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/025.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/back/pikachub.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/060.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/back/poliwagb.pic"
PsyduckPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/054.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/back/psyduckb.pic"
QwilfishPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/211.pic"
QwilfishPicBack::     INCBIN "gfx/pokemon/back/qwilfishb.pic"
RattataPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/019.pic"
RattataPicBack::      INCBIN "gfx/pokemon/back/rattatab.pic"
RemoraidPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/223.pic"
RemoraidPicBack::     INCBIN "gfx/pokemon/back/remoraidb.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/027.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/back/sandshrewb.pic"
ShellderPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/090.pic"
ShellderPicBack::     INCBIN "gfx/pokemon/back/shellderb.pic"
SlowpokePicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/079.pic"
SlowpokePicBack::     INCBIN "gfx/pokemon/back/slowpokeb.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/021.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/back/spearowb.pic"
SpinarakPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/167.pic"
SpinarakPicBack::     INCBIN "gfx/pokemon/back/spinarakb.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/007.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/back/squirtleb.pic"
TentacoolPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/072.pic"
TentacoolPicBack::    INCBIN "gfx/pokemon/back/tentacoolb.pic"
TogepiPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/175.pic"
TogepiPicBack::       INCBIN "gfx/pokemon/back/togepib.pic"
ENDC


SECTION "Pics 8", ROMX

IF DEF(_SATURN)
BayleefPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/153.pic"
BayleefPicBack::      INCBIN "gfx/pokemon/back/bayleefb.pic"
ChanseyPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/113.pic"
ChanseyPicBack::      INCBIN "gfx/pokemon/back/chanseyb.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/005.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/back/charmeleonb.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/036.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/back/clefableb.pic"
DewgongPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/087.pic"
DewgongPicBack::      INCBIN "gfx/pokemon/back/dewgongb.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/148.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/back/dragonairb.pic"
DrowzeePicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/096.pic"
DrowzeePicBack::      INCBIN "gfx/pokemon/back/drowzeeb.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/051.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/back/dugtriob.pic"
ElectabuzzPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/125.pic"
ElectabuzzPicBack::   INCBIN "gfx/pokemon/back/electabuzzb.pic"
EspeonPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/196.pic"
EspeonPicBack::       INCBIN "gfx/pokemon/back/espeonb.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/048.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/back/venonatb.pic"
VoltorbPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/100.pic"
VoltorbPicBack::      INCBIN "gfx/pokemon/back/voltorbb.pic"
WeedlePicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/013.pic"
WeedlePicBack::       INCBIN "gfx/pokemon/back/weedleb.pic"
ZubatPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/041.pic"
ZubatPicBack::        INCBIN "gfx/pokemon/back/zubatb.pic"
ENDC
IF DEF(_MARS)
BayleefPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/153.pic"
BayleefPicBack::      INCBIN "gfx/pokemon/back/bayleefb.pic"
ChanseyPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/113.pic"
ChanseyPicBack::      INCBIN "gfx/pokemon/back/chanseyb.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/005.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/back/charmeleonb.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/036.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/back/clefableb.pic"
DewgongPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/087.pic"
DewgongPicBack::      INCBIN "gfx/pokemon/back/dewgongb.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/148.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/back/dragonairb.pic"
DrowzeePicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/096.pic"
DrowzeePicBack::      INCBIN "gfx/pokemon/back/drowzeeb.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/051.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/back/dugtriob.pic"
ElectabuzzPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/125.pic"
ElectabuzzPicBack::   INCBIN "gfx/pokemon/back/electabuzzb.pic"
EspeonPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/196.pic"
EspeonPicBack::       INCBIN "gfx/pokemon/back/espeonb.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/048.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/back/venonatb.pic"
VoltorbPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/100.pic"
VoltorbPicBack::      INCBIN "gfx/pokemon/back/voltorbb.pic"
WeedlePicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/013.pic"
WeedlePicBack::       INCBIN "gfx/pokemon/back/weedleb.pic"
ZubatPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/041.pic"
ZubatPicBack::        INCBIN "gfx/pokemon/back/zubatb.pic"
ENDC


SECTION "Pics 9", ROMX

IF DEF(_SATURN)
FarfetchdPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/083.pic"
FarfetchdPicBack::    INCBIN "gfx/pokemon/back/farfetchdb.pic"
FlaaffyPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/180.pic"
FlaaffyPicBack::      INCBIN "gfx/pokemon/back/flaaffyb.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/136.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/back/flareonb.pic"
GengarPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/094.pic"
GengarPicBack::       INCBIN "gfx/pokemon/back/gengarb.pic"
GloomPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/044.pic"
GloomPicBack::        INCBIN "gfx/pokemon/back/gloomb.pic"
GoldeenPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/118.pic"
GoldeenPicBack::      INCBIN "gfx/pokemon/back/goldeenb.pic"
GolemPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/076.pic"
GolemPicBack::        INCBIN "gfx/pokemon/back/golemb.pic"
GravelerPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/075.pic"
GravelerPicBack::     INCBIN "gfx/pokemon/back/gravelerb.pic"
HaunterPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/093.pic"
HaunterPicBack::      INCBIN "gfx/pokemon/back/haunterb.pic"
HitmonchanPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/107.pic"
HitmonchanPicBack::   INCBIN "gfx/pokemon/back/hitmonchanb.pic"
HoundoomPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/229.pic"
HoundoomPicBack::     INCBIN "gfx/pokemon/back/houndoomb.pic"
HoundourPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/228.pic"
HoundourPicBack::     INCBIN "gfx/pokemon/back/houndourb.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/002.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/back/ivysaurb.pic"
JolteonPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/135.pic"
JolteonPicBack::      INCBIN "gfx/pokemon/back/jolteonb.pic"
ENDC
IF DEF(_MARS)
FarfetchdPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/083.pic"
FarfetchdPicBack::    INCBIN "gfx/pokemon/back/farfetchdb.pic"
FlaaffyPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/180.pic"
FlaaffyPicBack::      INCBIN "gfx/pokemon/back/flaaffyb.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/136.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/back/flareonb.pic"
GengarPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/094.pic"
GengarPicBack::       INCBIN "gfx/pokemon/back/gengarb.pic"
GloomPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/044.pic"
GloomPicBack::        INCBIN "gfx/pokemon/back/gloomb.pic"
GoldeenPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/118.pic"
GoldeenPicBack::      INCBIN "gfx/pokemon/back/goldeenb.pic"
GolemPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/076.pic"
GolemPicBack::        INCBIN "gfx/pokemon/back/golemb.pic"
GravelerPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/075.pic"
GravelerPicBack::     INCBIN "gfx/pokemon/back/gravelerb.pic"
HaunterPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/093.pic"
HaunterPicBack::      INCBIN "gfx/pokemon/back/haunterb.pic"
HitmonchanPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/107.pic"
HitmonchanPicBack::   INCBIN "gfx/pokemon/back/hitmonchanb.pic"
HoundoomPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/229.pic"
HoundoomPicBack::     INCBIN "gfx/pokemon/back/houndoomb.pic"
HoundourPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/228.pic"
HoundourPicBack::     INCBIN "gfx/pokemon/back/houndourb.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/002.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/back/ivysaurb.pic"
JolteonPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/135.pic"
JolteonPicBack::      INCBIN "gfx/pokemon/back/jolteonb.pic"
ENDC


SECTION "Pics 10", ROMX

IF DEF(_SATURN)
HypnoPicFront::       INCBIN "gfx/pokemon/front_saturn_1st_generation/097.pic"
HypnoPicBack::        INCBIN "gfx/pokemon/back/hypnob.pic"
JynxPicFront::        INCBIN "gfx/pokemon/front_saturn_1st_generation/124.pic"
JynxPicBack::         INCBIN "gfx/pokemon/back/jynxb.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/141.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/back/kabutopsb.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/064.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/back/kadabrab.pic"
KoffingPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/109.pic"
KoffingPicBack::      INCBIN "gfx/pokemon/back/koffingb.pic"
LeafeonPicFront::     INCBIN "gfx/pokemon/front_saturn_4th_generation/470.pic"
LeafeonPicBack::      INCBIN "gfx/pokemon/back/leafeonb.pic"
LedianPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/166.pic"
LedianPicBack::       INCBIN "gfx/pokemon/back/ledianb.pic"
LedybaPicFront::      INCBIN "gfx/pokemon/front_saturn_2nd_generation/165.pic"
LedybaPicBack::       INCBIN "gfx/pokemon/back/ledybab.pic"
MagikarpPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/129.pic"
MagikarpPicBack::     INCBIN "gfx/pokemon/back/magikarpb.pic"
MagmarPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/126.pic"
MagmarPicBack::       INCBIN "gfx/pokemon/back/magmarb.pic"
MagnetonPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/082.pic"
MagnetonPicBack::     INCBIN "gfx/pokemon/back/magnetonb.pic"
MarowakPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/105.pic"
MarowakPicBack::      INCBIN "gfx/pokemon/back/marowakb.pic"
MiltankPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/241.pic"
MiltankPicBack::      INCBIN "gfx/pokemon/back/miltankb.pic"
MrMimePicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/122.pic"
MrMimePicBack::       INCBIN "gfx/pokemon/back/mr.mimeb.pic"
ENDC
IF DEF(_MARS)
HypnoPicFront::       INCBIN "gfx/pokemon/front_mars_1st_generation/097.pic"
HypnoPicBack::        INCBIN "gfx/pokemon/back/hypnob.pic"
JynxPicFront::        INCBIN "gfx/pokemon/front_mars_1st_generation/124.pic"
JynxPicBack::         INCBIN "gfx/pokemon/back/jynxb.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/141.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/back/kabutopsb.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/064.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/back/kadabrab.pic"
KoffingPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/109.pic"
KoffingPicBack::      INCBIN "gfx/pokemon/back/koffingb.pic"
LeafeonPicFront::     INCBIN "gfx/pokemon/front_mars_4th_generation/470.pic"
LeafeonPicBack::      INCBIN "gfx/pokemon/back/leafeonb.pic"
LedianPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/166.pic"
LedianPicBack::       INCBIN "gfx/pokemon/back/ledianb.pic"
LedybaPicFront::      INCBIN "gfx/pokemon/front_mars_2nd_generation/165.pic"
LedybaPicBack::       INCBIN "gfx/pokemon/back/ledybab.pic"
MagikarpPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/129.pic"
MagikarpPicBack::     INCBIN "gfx/pokemon/back/magikarpb.pic"
MagmarPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/126.pic"
MagmarPicBack::       INCBIN "gfx/pokemon/back/magmarb.pic"
MagnetonPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/082.pic"
MagnetonPicBack::     INCBIN "gfx/pokemon/back/magnetonb.pic"
MarowakPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/105.pic"
MarowakPicBack::      INCBIN "gfx/pokemon/back/marowakb.pic"
MiltankPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/241.pic"
MiltankPicBack::      INCBIN "gfx/pokemon/back/miltankb.pic"
MrMimePicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/122.pic"
MrMimePicBack::       INCBIN "gfx/pokemon/back/mr.mimeb.pic"
ENDC


SECTION "Pics 11", ROMX

IF DEF(_SATURN)
KangaskhanPicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/115.pic"
KangaskhanPicBack::   INCBIN "gfx/pokemon/back/kangaskhanb.pic"
KinglerPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/099.pic"
KinglerPicBack::      INCBIN "gfx/pokemon/back/kinglerb.pic"
LaprasPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/131.pic"
LaprasPicBack::       INCBIN "gfx/pokemon/back/laprasb.pic"
LickitungPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/108.pic"
LickitungPicBack::    INCBIN "gfx/pokemon/back/lickitungb.pic"
MachampPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/068.pic"
MachampPicBack::      INCBIN "gfx/pokemon/back/machampb.pic"
MachokePicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/067.pic"
MachokePicBack::      INCBIN "gfx/pokemon/back/machokeb.pic"
MeganiumPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/154.pic"
MeganiumPicBack::     INCBIN "gfx/pokemon/back/meganiumb.pic"
MewtwoPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/150.pic"
MewtwoPicBack::       INCBIN "gfx/pokemon/back/mewtwob.pic"
MoltresPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/146.pic"
MoltresPicBack::      INCBIN "gfx/pokemon/back/moltresb.pic"
MukPicFront::         INCBIN "gfx/pokemon/front_saturn_1st_generation/089.pic"
MukPicBack::          INCBIN "gfx/pokemon/back/mukb.pic"
NidokingPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/034.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/back/nidokingb.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/031.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/back/nidoqueenb.pic"
ENDC
IF DEF(_MARS)
KangaskhanPicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/115.pic"
KangaskhanPicBack::   INCBIN "gfx/pokemon/back/kangaskhanb.pic"
KinglerPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/099.pic"
KinglerPicBack::      INCBIN "gfx/pokemon/back/kinglerb.pic"
LaprasPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/131.pic"
LaprasPicBack::       INCBIN "gfx/pokemon/back/laprasb.pic"
LickitungPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/108.pic"
LickitungPicBack::    INCBIN "gfx/pokemon/back/lickitungb.pic"
MachampPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/068.pic"
MachampPicBack::      INCBIN "gfx/pokemon/back/machampb.pic"
MachokePicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/067.pic"
MachokePicBack::      INCBIN "gfx/pokemon/back/machokeb.pic"
MeganiumPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/154.pic"
MeganiumPicBack::     INCBIN "gfx/pokemon/back/meganiumb.pic"
MewtwoPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/150.pic"
MewtwoPicBack::       INCBIN "gfx/pokemon/back/mewtwob.pic"
MoltresPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/146.pic"
MoltresPicBack::      INCBIN "gfx/pokemon/back/moltresb.pic"
MukPicFront::         INCBIN "gfx/pokemon/front_mars_1st_generation/089.pic"
MukPicBack::          INCBIN "gfx/pokemon/back/mukb.pic"
NidokingPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/034.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/back/nidokingb.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/031.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/back/nidoqueenb.pic"
ENDC


SECTION "Pics 12", ROMX

IF DEF(_SATURN)
NidorinaPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/030.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/back/nidorinab.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/033.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/back/nidorinob.pic"
OctilleryPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/224.pic"
OctilleryPicBack::    INCBIN "gfx/pokemon/back/octilleryb.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/139.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/back/omastarb.pic"
PidgeottoPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/017.pic"
PidgeottoPicBack::    INCBIN "gfx/pokemon/back/pidgeottob.pic"
PoliwhirlPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/061.pic"
PoliwhirlPicBack::    INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PonytaPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/077.pic"
PonytaPicBack::       INCBIN "gfx/pokemon/back/ponytab.pic"
PorygonPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/137.pic"
PorygonPicBack::      INCBIN "gfx/pokemon/back/porygonb.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/020.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/back/raticateb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/028.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/back/sandslashb.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/117.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/back/seadrab.pic"
SeelPicFront::        INCBIN "gfx/pokemon/front_saturn_1st_generation/086.pic"
SeelPicBack::         INCBIN "gfx/pokemon/back/seelb.pic"
SnubbullPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/209.pic"
SnubbullPicBack::     INCBIN "gfx/pokemon/back/snubbullb.pic"
StarmiePicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/121.pic"
StarmiePicBack::      INCBIN "gfx/pokemon/back/starmieb.pic"
ENDC
IF DEF(_MARS)
NidorinaPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/030.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/back/nidorinab.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/033.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/back/nidorinob.pic"
OctilleryPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/224.pic"
OctilleryPicBack::    INCBIN "gfx/pokemon/back/octilleryb.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/139.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/back/omastarb.pic"
PidgeottoPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/017.pic"
PidgeottoPicBack::    INCBIN "gfx/pokemon/back/pidgeottob.pic"
PoliwhirlPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/061.pic"
PoliwhirlPicBack::    INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PonytaPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/077.pic"
PonytaPicBack::       INCBIN "gfx/pokemon/back/ponytab.pic"
PorygonPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/137.pic"
PorygonPicBack::      INCBIN "gfx/pokemon/back/porygonb.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/020.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/back/raticateb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/028.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/back/sandslashb.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/117.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/back/seadrab.pic"
SeelPicFront::        INCBIN "gfx/pokemon/front_mars_1st_generation/086.pic"
SeelPicBack::         INCBIN "gfx/pokemon/back/seelb.pic"
SnubbullPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/209.pic"
SnubbullPicBack::     INCBIN "gfx/pokemon/back/snubbullb.pic"
StarmiePicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/121.pic"
StarmiePicBack::      INCBIN "gfx/pokemon/back/starmieb.pic"
ENDC


SECTION "Pics 13", ROMX

IF DEF(_SATURN)
NinetalesPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/038.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/back/ninetalesb.pic"
NoctowlPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/164.pic"
NoctowlPicBack::      INCBIN "gfx/pokemon/back/noctowlb.pic"
OnixPicFront::        INCBIN "gfx/pokemon/front_saturn_1st_generation/095.pic"
OnixPicBack::         INCBIN "gfx/pokemon/back/onixb.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/047.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/back/parasectb.pic"
PersianPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/053.pic"
PersianPicBack::      INCBIN "gfx/pokemon/back/persianb.pic"
PidgeotPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/018.pic"
PidgeotPicBack::      INCBIN "gfx/pokemon/back/pidgeotb.pic"
PinsirPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/127.pic"
PinsirPicBack::       INCBIN "gfx/pokemon/back/pinsirb.pic"
PoliwrathPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/062.pic"
PoliwrathPicBack::    INCBIN "gfx/pokemon/back/poliwrathb.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/057.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/back/primeapeb.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/026.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/back/raichub.pic"
StaryuPicFront::      INCBIN "gfx/pokemon/front_saturn_1st_generation/120.pic"
StaryuPicBack::       INCBIN "gfx/pokemon/back/staryub.pic"
SunfloraPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/192.pic"
SunfloraPicBack::     INCBIN "gfx/pokemon/back/sunflorab.pic"
ENDC
IF DEF(_MARS)
NinetalesPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/038.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/back/ninetalesb.pic"
NoctowlPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/164.pic"
NoctowlPicBack::      INCBIN "gfx/pokemon/back/noctowlb.pic"
OnixPicFront::        INCBIN "gfx/pokemon/front_mars_1st_generation/095.pic"
OnixPicBack::         INCBIN "gfx/pokemon/back/onixb.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/047.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/back/parasectb.pic"
PersianPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/053.pic"
PersianPicBack::      INCBIN "gfx/pokemon/back/persianb.pic"
PidgeotPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/018.pic"
PidgeotPicBack::      INCBIN "gfx/pokemon/back/pidgeotb.pic"
PinsirPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/127.pic"
PinsirPicBack::       INCBIN "gfx/pokemon/back/pinsirb.pic"
PoliwrathPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/062.pic"
PoliwrathPicBack::    INCBIN "gfx/pokemon/back/poliwrathb.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/057.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/back/primeapeb.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/026.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/back/raichub.pic"
StaryuPicFront::      INCBIN "gfx/pokemon/front_mars_1st_generation/120.pic"
StaryuPicBack::       INCBIN "gfx/pokemon/back/staryub.pic"
SunfloraPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/192.pic"
SunfloraPicBack::     INCBIN "gfx/pokemon/back/sunflorab.pic"
ENDC


SECTION "Pics 14", ROMX

IF DEF(_SATURN)
RapidashPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/078.pic"
RapidashPicBack::    INCBIN "gfx/pokemon/back/rapidashb.pic"
RhydonPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/112.pic"
RhydonPicBack::      INCBIN "gfx/pokemon/back/rhydonb.pic"
ScizorPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/212.pic"
ScizorPicBack::      INCBIN "gfx/pokemon/back/scizorb.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/123.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/back/scytherb.pic"
SeakingPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/119.pic"
SeakingPicBack::     INCBIN "gfx/pokemon/back/seakingb.pic"
SkarmoryPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/227.pic"
SkarmoryPicBack::    INCBIN "gfx/pokemon/back/skarmoryb.pic"
SlowbroPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/080.pic"
SlowbroPicBack::     INCBIN "gfx/pokemon/back/slowbrob.pic"
SlowkingPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/199.pic"
SlowkingPicBack::    INCBIN "gfx/pokemon/back/slowkingb.pic"
SmearglePicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/235.pic"
SmearglePicBack::    INCBIN "gfx/pokemon/back/smeargleb.pic"
SnorlaxPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/143.pic"
SnorlaxPicBack::     INCBIN "gfx/pokemon/back/snorlaxb.pic"
SteelixPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/208.pic"
SteelixPicBack::     INCBIN "gfx/pokemon/back/steelixb.pic"
TaurosPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/128.pic"
TaurosPicBack::      INCBIN "gfx/pokemon/back/taurosb.pic"
ENDC
IF DEF(_MARS)
RapidashPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/078.pic"
RapidashPicBack::    INCBIN "gfx/pokemon/back/rapidashb.pic"
RhydonPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/112.pic"
RhydonPicBack::      INCBIN "gfx/pokemon/back/rhydonb.pic"
ScizorPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/212.pic"
ScizorPicBack::      INCBIN "gfx/pokemon/back/scizorb.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/123.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/back/scytherb.pic"
SeakingPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/119.pic"
SeakingPicBack::     INCBIN "gfx/pokemon/back/seakingb.pic"
SkarmoryPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/227.pic"
SkarmoryPicBack::    INCBIN "gfx/pokemon/back/skarmoryb.pic"
SlowbroPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/080.pic"
SlowbroPicBack::     INCBIN "gfx/pokemon/back/slowbrob.pic"
SlowkingPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/199.pic"
SlowkingPicBack::    INCBIN "gfx/pokemon/back/slowkingb.pic"
SmearglePicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/235.pic"
SmearglePicBack::    INCBIN "gfx/pokemon/back/smeargleb.pic"
SnorlaxPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/143.pic"
SnorlaxPicBack::     INCBIN "gfx/pokemon/back/snorlaxb.pic"
SteelixPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/208.pic"
SteelixPicBack::     INCBIN "gfx/pokemon/back/steelixb.pic"
TaurosPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/128.pic"
TaurosPicBack::      INCBIN "gfx/pokemon/back/taurosb.pic"
ENDC


SECTION "Pics 15", ROMX

IF DEF(_SATURN)
ChinchouPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/170.pic"
ChinchouPicBack::    INCBIN "gfx/pokemon/back/chinchoub.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/114.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/back/tangelab.pic"
TentacruelPicFront:: INCBIN "gfx/pokemon/front_saturn_1st_generation/073.pic"
TentacruelPicBack::  INCBIN "gfx/pokemon/back/tentacruelb.pic"
UmbreonPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/197.pic"
UmbreonPicBack::     INCBIN "gfx/pokemon/back/umbreonb.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/134.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/back/vaporeonb.pic"
VenomothPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/049.pic"
VenomothPicBack::    INCBIN "gfx/pokemon/back/venomothb.pic"
VenusaurPicFront::   INCBIN "gfx/pokemon/front_saturn_1st_generation/003.pic"
VenusaurPicBack::    INCBIN "gfx/pokemon/back/venusaurb.pic"
VictreebelPicFront:: INCBIN "gfx/pokemon/front_saturn_1st_generation/071.pic"
VictreebelPicBack::  INCBIN "gfx/pokemon/back/victreebelb.pic"
VulpixPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/037.pic"
VulpixPicBack::      INCBIN "gfx/pokemon/back/vulpixb.pic"
WartortlePicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/008.pic"
WartortlePicBack::   INCBIN "gfx/pokemon/back/wartortleb.pic"
WeepinbellPicFront:: INCBIN "gfx/pokemon/front_saturn_1st_generation/070.pic"
WeepinbellPicBack::  INCBIN "gfx/pokemon/back/weepinbellb.pic"
WigglytuffPicFront:: INCBIN "gfx/pokemon/front_saturn_1st_generation/040.pic"
WigglytuffPicBack::  INCBIN "gfx/pokemon/back/wigglytuffb.pic"
XatuPicFront::       INCBIN "gfx/pokemon/front_saturn_2nd_generation/178.pic"
XatuPicBack::        INCBIN "gfx/pokemon/back/xatub.pic"
ENDC
IF DEF(_MARS)
ChinchouPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/170.pic"
ChinchouPicBack::    INCBIN "gfx/pokemon/back/chinchoub.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/114.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/back/tangelab.pic"
TentacruelPicFront:: INCBIN "gfx/pokemon/front_mars_1st_generation/073.pic"
TentacruelPicBack::  INCBIN "gfx/pokemon/back/tentacruelb.pic"
UmbreonPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/197.pic"
UmbreonPicBack::     INCBIN "gfx/pokemon/back/umbreonb.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/134.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/back/vaporeonb.pic"
VenomothPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/049.pic"
VenomothPicBack::    INCBIN "gfx/pokemon/back/venomothb.pic"
VenusaurPicFront::   INCBIN "gfx/pokemon/front_mars_1st_generation/003.pic"
VenusaurPicBack::    INCBIN "gfx/pokemon/back/venusaurb.pic"
VictreebelPicFront:: INCBIN "gfx/pokemon/front_mars_1st_generation/071.pic"
VictreebelPicBack::  INCBIN "gfx/pokemon/back/victreebelb.pic"
VulpixPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/037.pic"
VulpixPicBack::      INCBIN "gfx/pokemon/back/vulpixb.pic"
WartortlePicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/008.pic"
WartortlePicBack::   INCBIN "gfx/pokemon/back/wartortleb.pic"
WeepinbellPicFront:: INCBIN "gfx/pokemon/front_mars_1st_generation/070.pic"
WeepinbellPicBack::  INCBIN "gfx/pokemon/back/weepinbellb.pic"
WigglytuffPicFront:: INCBIN "gfx/pokemon/front_mars_1st_generation/040.pic"
WigglytuffPicBack::  INCBIN "gfx/pokemon/back/wigglytuffb.pic"
XatuPicFront::       INCBIN "gfx/pokemon/front_mars_2nd_generation/178.pic"
XatuPicBack::        INCBIN "gfx/pokemon/back/xatub.pic"
ENDC


SECTION "Pics 16", ROMX

IF DEF(_SATURN)
RhyhornPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/111.pic"
RhyhornPicBack::     INCBIN "gfx/pokemon/back/rhyhornb.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/front_saturn_1st_generation/045.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/back/vileplumeb.pic"
WeezingPicFront::    INCBIN "gfx/pokemon/front_saturn_1st_generation/110.pic"
WeezingPicBack::     INCBIN "gfx/pokemon/back/weezingb.pic"
ZapdosPicFront::     INCBIN "gfx/pokemon/front_saturn_1st_generation/145.pic"
ZapdosPicBack::      INCBIN "gfx/pokemon/back/zapdosb.pic"
QuilavaPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/156.pic"
QuilavaPicBack::     INCBIN "gfx/pokemon/back/quilavab.pic"
TyphlosionPicFront:: INCBIN "gfx/pokemon/front_saturn_2nd_generation/157.pic"
TyphlosionPicBack::  INCBIN "gfx/pokemon/back/typhlosionb.pic"
TotodilePicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/158.pic"
TotodilePicBack::    INCBIN "gfx/pokemon/back/totodileb.pic"
CroconawPicFront::   INCBIN "gfx/pokemon/front_saturn_2nd_generation/159.pic"
CroconawPicBack::    INCBIN "gfx/pokemon/back/croconawb.pic"
FeraligatrPicFront:: INCBIN "gfx/pokemon/front_saturn_2nd_generation/160.pic"
FeraligatrPicBack::  INCBIN "gfx/pokemon/back/feraligatrb.pic"
SentretPicFront::    INCBIN "gfx/pokemon/front_saturn_2nd_generation/161.pic"
SentretPicBack::     INCBIN "gfx/pokemon/back/sentretb.pic"
FurretPicFront::     INCBIN "gfx/pokemon/front_saturn_2nd_generation/162.pic"
FurretPicBack::      INCBIN "gfx/pokemon/back/furretb.pic"
SudowoodoPicFront::  INCBIN "gfx/pokemon/front_saturn_2nd_generation/185.pic"
SudowoodoPicBack::   INCBIN "gfx/pokemon/back/sudowoodob.pic"
ENDC
IF DEF(_MARS)
RhyhornPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/111.pic"
RhyhornPicBack::     INCBIN "gfx/pokemon/back/rhyhornb.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/front_mars_1st_generation/045.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/back/vileplumeb.pic"
WeezingPicFront::    INCBIN "gfx/pokemon/front_mars_1st_generation/110.pic"
WeezingPicBack::     INCBIN "gfx/pokemon/back/weezingb.pic"
ZapdosPicFront::     INCBIN "gfx/pokemon/front_mars_1st_generation/145.pic"
ZapdosPicBack::      INCBIN "gfx/pokemon/back/zapdosb.pic"
QuilavaPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/156.pic"
QuilavaPicBack::     INCBIN "gfx/pokemon/back/quilavab.pic"
TyphlosionPicFront:: INCBIN "gfx/pokemon/front_mars_2nd_generation/157.pic"
TyphlosionPicBack::  INCBIN "gfx/pokemon/back/typhlosionb.pic"
TotodilePicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/158.pic"
TotodilePicBack::    INCBIN "gfx/pokemon/back/totodileb.pic"
CroconawPicFront::   INCBIN "gfx/pokemon/front_mars_2nd_generation/159.pic"
CroconawPicBack::    INCBIN "gfx/pokemon/back/croconawb.pic"
FeraligatrPicFront:: INCBIN "gfx/pokemon/front_mars_2nd_generation/160.pic"
FeraligatrPicBack::  INCBIN "gfx/pokemon/back/feraligatrb.pic"
SentretPicFront::    INCBIN "gfx/pokemon/front_mars_2nd_generation/161.pic"
SentretPicBack::     INCBIN "gfx/pokemon/back/sentretb.pic"
FurretPicFront::     INCBIN "gfx/pokemon/front_mars_2nd_generation/162.pic"
FurretPicBack::      INCBIN "gfx/pokemon/back/furretb.pic"
SudowoodoPicFront::  INCBIN "gfx/pokemon/front_mars_2nd_generation/185.pic"
SudowoodoPicBack::   INCBIN "gfx/pokemon/back/sudowoodob.pic"
ENDC


SECTION "Pics 6", ROMX

YoungsterPic::     INCBIN "gfx/trainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/trainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/trainers/lass.pic"
SailorPic::        INCBIN "gfx/trainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/trainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/trainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/trainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/trainers/supernerd.pic"
HikerPic::         INCBIN "gfx/trainers/hiker.pic"
BikerPic::         INCBIN "gfx/trainers/biker.pic"
BurglarPic::       INCBIN "gfx/trainers/burglar.pic"
EngineerPic::      INCBIN "gfx/trainers/engineer.pic"
FisherPic::        INCBIN "gfx/trainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/trainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/trainers/cueball.pic"
GamblerPic::       INCBIN "gfx/trainers/gambler.pic"
BeautyPic::        INCBIN "gfx/trainers/beauty.pic"
PsychicPic::       INCBIN "gfx/trainers/psychic.pic"
RockerPic::        INCBIN "gfx/trainers/rocker.pic"
JugglerPic::       INCBIN "gfx/trainers/juggler.pic"
TamerPic::         INCBIN "gfx/trainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/trainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/trainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/trainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/trainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/trainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/trainers/giovanni.pic"
RocketPic::        INCBIN "gfx/trainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/trainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/trainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/trainers/bruno.pic"
BrockPic::         INCBIN "gfx/trainers/brock.pic"
MistyPic::         INCBIN "gfx/trainers/misty.pic"
LtSurgePic::       INCBIN "gfx/trainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/trainers/erika.pic"
KogaPic::          INCBIN "gfx/trainers/koga.pic"
BlainePic::        INCBIN "gfx/trainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/trainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/trainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/trainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/trainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/trainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/trainers/channeler.pic"
AgathaPic::        INCBIN "gfx/trainers/agatha.pic"
LancePic::         INCBIN "gfx/trainers/lance.pic"
