SECTION "NPC Sprites 1", ROMX

AaSprite::              INCBIN "gfx/sprites/aa.2bpp"
AbSprite::              INCBIN "gfx/sprites/ab.2bpp"

BaSprite::              INCBIN "gfx/sprites/ba.2bpp"

AaBikeSprite::          INCBIN "gfx/sprites/aa_bike.2bpp"
AbBikeSprite::          INCBIN "gfx/sprites/ab_bike.2bpp"

Barman1Sprite::         INCBIN "gfx/sprites/barman1.2bpp"
Barman2Sprite::         INCBIN "gfx/sprites/barman2.2bpp"
BrunetteGirlSprite::    INCBIN "gfx/sprites/brunette_girl.2bpp"
CaptainSprite::         INCBIN "gfx/sprites/captain.2bpp"
CookSprite::            INCBIN "gfx/sprites/cuca.2bpp"
DanpeiSprite::          INCBIN "gfx/sprites/danpei_tange.2bpp"
FatManSprite::          INCBIN "gfx/sprites/fat_man.2bpp"
FishingGuruSprite::     INCBIN "gfx/sprites/fishing_guru.2bpp"
GameBoyFSprite::        INCBIN "gfx/sprites/gameboy_f.2bpp"
GameBoyMSprite::        INCBIN "gfx/sprites/gameboy_m.2bpp"
GrampsSprite::          INCBIN "gfx/sprites/gramps.2bpp"
GrandmaSprite::         INCBIN "gfx/sprites/grandma.2bpp"
ManSprite::             INCBIN "gfx/sprites/man.2bpp"
MiddleAgedManSprite::   INCBIN "gfx/sprites/middle_aged_man.2bpp"
MiddleAgedWomanSprite:: INCBIN "gfx/sprites/middle_aged_woman.2bpp"

NurseSprite::           INCBIN "gfx/sprites/nurse.2bpp"
OfficerSprite::         INCBIN "gfx/sprites/officer.2bpp"

SuperNerd1Sprite::      INCBIN "gfx/sprites/super_nerd1.2bpp"
SuperNerd2Sprite::      INCBIN "gfx/sprites/super_nerd2.2bpp"
WomanSprite::           INCBIN "gfx/sprites/woman.2bpp"
Youngster2Sprite::      INCBIN "gfx/sprites/youngster2.2bpp"

ZoneWorkerSprite::      INCBIN "gfx/sprites/zone_worker.2bpp"

BeautySprite::          INCBIN "gfx/sprites/beauty.2bpp"
BikerSprite::           INCBIN "gfx/sprites/biker.2bpp"
BirdKeeperFSprite::     INCBIN "gfx/sprites/birdkeeper_f.2bpp"
BirdKeeperMSprite::     INCBIN "gfx/sprites/birdkeeper_m.2bpp"
BlackBeltFSprite::      INCBIN "gfx/sprites/blackbelt_f.2bpp"
BlackBeltMSprite::      INCBIN "gfx/sprites/blackbelt_m.2bpp"
BugCatcherFSprite::     INCBIN "gfx/sprites/bugcatcher_f.2bpp"
BugCatcherMSprite::     INCBIN "gfx/sprites/bugcatcher_m.2bpp"
BurglarSprite::         INCBIN "gfx/sprites/burglar.2bpp"
ChannelerSprite::       INCBIN "gfx/sprites/channeler.2bpp"
CoolTrainerFSprite::    INCBIN "gfx/sprites/cooltrainer_f.2bpp"
CoolTrainerMSprite::    INCBIN "gfx/sprites/cooltrainer_m.2bpp"
CueBallSprite::         INCBIN "gfx/sprites/cue_ball.2bpp"
DelinquentSprite::      INCBIN "gfx/sprites/delinquent.2bpp"
EngineerSprite::        INCBIN "gfx/sprites/engineer.2bpp"
FisherSprite::          INCBIN "gfx/sprites/fisher.2bpp"
GamblerSprite::         INCBIN "gfx/sprites/gambler.2bpp"
GentlemanSprite::       INCBIN "gfx/sprites/gentleman.2bpp"

BookSprite::            INCBIN "gfx/sprites/first_still/book.2bpp"

BoulderSprite::         INCBIN "gfx/sprites/first_still/boulder.2bpp"

Fossil1Sprite::         INCBIN "gfx/sprites/first_still/fossil1.2bpp"

PokeBallSprite::        INCBIN "gfx/sprites/first_still/poke_ball.2bpp"


SECTION "NPC Sprites 2", ROMX

HikerSprite::           INCBIN "gfx/sprites/hiker.2bpp"
JrTrainerFSprite::      INCBIN "gfx/sprites/jr_trainer_f.2bpp"
JrTrainerMSprite::      INCBIN "gfx/sprites/jr_trainer_m.2bpp"
JugglerSprite::         INCBIN "gfx/sprites/juggler.2bpp"
KimonoGirlSprite::      INCBIN "gfx/sprites/kimono_girl.2bpp"
LassSprite::            INCBIN "gfx/sprites/lass.2bpp"
LittleBoySprite::       INCBIN "gfx/sprites/little_boy.2bpp"
LittleGirlSprite::      INCBIN "gfx/sprites/little_girl.2bpp"
PokeManiacFSprite::     INCBIN "gfx/sprites/pokemaniac_f.2bpp"
PokeManiacMSprite::     INCBIN "gfx/sprites/pokemaniac_m.2bpp"
PsychicFSprite::        INCBIN "gfx/sprites/psychic_f.2bpp"
PsychicMSprite::        INCBIN "gfx/sprites/psychic_m.2bpp"
RockerSprite::          INCBIN "gfx/sprites/rocker.2bpp"
SailorSprite::          INCBIN "gfx/sprites/sailor.2bpp"
ScientistFSprite::      INCBIN "gfx/sprites/scientist_f.2bpp"
ScientistMSprite::      INCBIN "gfx/sprites/scientist_m.2bpp"
SuperNerd3Sprite::      INCBIN "gfx/sprites/super_nerd3.2bpp"
SwimmerFSprite::        INCBIN "gfx/sprites/swimmer_f.2bpp"
SwimmerMSprite::        INCBIN "gfx/sprites/swimmer_m.2bpp"
TamerSprite::           INCBIN "gfx/sprites/tamer.2bpp"
Youngster1Sprite::      INCBIN "gfx/sprites/youngster1.2bpp"

VermelhoSprite::        INCBIN "gfx/sprites/vermelho.2bpp"
AzulSprite::            INCBIN "gfx/sprites/vermelho_mulher.2bpp"
VerdeSprite::           INCBIN "gfx/sprites/vermelho_rival.2bpp"

EvilGruntFSprite::      INCBIN "gfx/sprites/evilgrunt_f.2bpp"
EvilGruntMSprite::      INCBIN "gfx/sprites/evilgrunt_m.2bpp"
EvilBossSprite::        INCBIN "gfx/sprites/evilboss.2bpp"

DojoLeaderSprite::      INCBIN "gfx/sprites/dojo_leader.2bpp"

GymLeader1Sprite::      INCBIN "gfx/sprites/leader1.2bpp"
GymLeader2Sprite::      INCBIN "gfx/sprites/leader2.2bpp"
GymLeader3Sprite::      INCBIN "gfx/sprites/leader3.2bpp"
GymLeader4Sprite::      INCBIN "gfx/sprites/leader4.2bpp"
GymLeader5Sprite::      INCBIN "gfx/sprites/leader5.2bpp"
GymLeader6Sprite::      INCBIN "gfx/sprites/leader6.2bpp"
GymLeader7Sprite::      INCBIN "gfx/sprites/leader7.2bpp"
GymLeader8Sprite::      INCBIN "gfx/sprites/leader8.2bpp"

EliteFour1Sprite::      INCBIN "gfx/sprites/elitefour1.2bpp"
EliteFour2Sprite::      INCBIN "gfx/sprites/elitefour2.2bpp"
EliteFour3Sprite::      INCBIN "gfx/sprites/elitefour3.2bpp"
EliteFour4Sprite::      INCBIN "gfx/sprites/elitefour4.2bpp"

ArticunoSprite::        INCBIN "gfx/sprites/pokemon_ov/articuno.2bpp"
CuboneSprite::          INCBIN "gfx/sprites/pokemon_ov/cubone.2bpp"
HoohSprite::            INCBIN "gfx/sprites/pokemon_ov/hooh.2bpp"
JigglypuffSprite::      INCBIN "gfx/sprites/pokemon_ov/jigglypuff.2bpp"
LaprasSprite::          INCBIN "gfx/sprites/pokemon_ov/lapras.2bpp"
MachokeSprite::         INCBIN "gfx/sprites/pokemon_ov/machoke.2bpp"
MeowthSprite::          INCBIN "gfx/sprites/pokemon_ov/meowth.2bpp"
MewtwoSprite::          INCBIN "gfx/sprites/pokemon_ov/mewtwo.2bpp"
MoltresSprite::         INCBIN "gfx/sprites/pokemon_ov/moltres.2bpp"
NidoranMSprite::        INCBIN "gfx/sprites/pokemon_ov/nidoran_m.2bpp"
NidorinoSprite::        INCBIN "gfx/sprites/pokemon_ov/nidorino.2bpp"
PidgeotSprite::         INCBIN "gfx/sprites/pokemon_ov/pidgeot.2bpp"
PikachuSprite::         INCBIN "gfx/sprites/pokemon_ov/pikachu.2bpp"
PsyduckSprite::         INCBIN "gfx/sprites/pokemon_ov/psyduck.2bpp"
VoltorbSprite::         INCBIN "gfx/sprites/pokemon_ov/voltorb.2bpp"
WigglytuffSprite::      INCBIN "gfx/sprites/pokemon_ov/wigglytuff.2bpp"
ZapdosSprite::          INCBIN "gfx/sprites/pokemon_ov/zapdos.2bpp"

PokedexSprite::         INCBIN "gfx/sprites/first_still/pokedex.2bpp"

ReceptionistSprite::    INCBIN "gfx/sprites/first_still/receptionist.2bpp"

SlowpokeSprite::        INCBIN "gfx/sprites/pokemon_ov/slowpoke.2bpp"
SnorlaxSprite::         INCBIN "gfx/sprites/pokemon_ov/snorlax.2bpp"


SECTION "NPC Sprites 3", ROMX

BirdSprite::            INCBIN "gfx/sprites/pokemon_ov/bird.2bpp"
ChanseySprite::         INCBIN "gfx/sprites/pokemon_ov/chansey.2bpp"
ClefairySprite::        INCBIN "gfx/sprites/pokemon_ov/clefairy.2bpp"
DoduoSprite::           INCBIN "gfx/sprites/pokemon_ov/doduo.2bpp"
FearowSprite::          INCBIN "gfx/sprites/pokemon_ov/fearow.2bpp"
KangaskhanSprite::      INCBIN "gfx/sprites/pokemon_ov/kangaskhan.2bpp"
MachopSprite::          INCBIN "gfx/sprites/pokemon_ov/machop.2bpp"
NidoranFSprite::        INCBIN "gfx/sprites/pokemon_ov/nidoran_f.2bpp"
PidgeySprite::          INCBIN "gfx/sprites/pokemon_ov/pidgey.2bpp"
PoliwrathSprite::       INCBIN "gfx/sprites/pokemon_ov/poliwrath.2bpp"
RhydonSprite::          INCBIN "gfx/sprites/pokemon_ov/rhydon.2bpp"
SeelSprite::            INCBIN "gfx/sprites/pokemon_ov/seel.2bpp"
SpearowSprite::         INCBIN "gfx/sprites/pokemon_ov/spearow.2bpp"

Special1Sprite::        INCBIN "gfx/sprites/special1.2bpp"
Special2Sprite::        INCBIN "gfx/sprites/special2.2bpp"
Special4Sprite::        INCBIN "gfx/sprites/special4.2bpp"
Special7Sprite::        INCBIN "gfx/sprites/special7.2bpp"

SatoshiSprite::         INCBIN "gfx/sprites/satoshi.2bpp"


SECTION "Icons Rapaz", ROMX

MonIcons::
INCBIN "gfx/icons/null.2bpp"
INCBIN "gfx/icons/bulbasaur.2bpp"
INCBIN "gfx/icons/ivysaur.2bpp"
INCBIN "gfx/icons/venusaur.2bpp"
INCBIN "gfx/icons/charmander.2bpp"
INCBIN "gfx/icons/charmeleon.2bpp"
INCBIN "gfx/icons/charizard.2bpp"
INCBIN "gfx/icons/squirtle.2bpp"
INCBIN "gfx/icons/wartortle.2bpp"
INCBIN "gfx/icons/blastoise.2bpp"
INCBIN "gfx/icons/caterpie.2bpp"
INCBIN "gfx/icons/metapod.2bpp"
INCBIN "gfx/icons/butterfree.2bpp"
INCBIN "gfx/icons/weedle.2bpp"
INCBIN "gfx/icons/kakuna.2bpp"
INCBIN "gfx/icons/beedrill.2bpp"
INCBIN "gfx/icons/pidgey.2bpp"
INCBIN "gfx/icons/pidgeotto.2bpp"
INCBIN "gfx/icons/pidgeot.2bpp"
INCBIN "gfx/icons/rattata.2bpp"
INCBIN "gfx/icons/raticate.2bpp"
INCBIN "gfx/icons/spearow.2bpp"
INCBIN "gfx/icons/fearow.2bpp"
INCBIN "gfx/icons/ekans.2bpp"
INCBIN "gfx/icons/arbok.2bpp"
INCBIN "gfx/icons/pikachu.2bpp"
INCBIN "gfx/icons/raichu.2bpp"
INCBIN "gfx/icons/sandshrew.2bpp"
INCBIN "gfx/icons/sandslash.2bpp"
INCBIN "gfx/icons/nidoran_f.2bpp"
INCBIN "gfx/icons/nidorina.2bpp"
INCBIN "gfx/icons/nidoqueen.2bpp"
INCBIN "gfx/icons/nidoran_m.2bpp"
INCBIN "gfx/icons/nidorino.2bpp"
INCBIN "gfx/icons/nidoking.2bpp"
INCBIN "gfx/icons/clefairy.2bpp"
INCBIN "gfx/icons/clefable.2bpp"
INCBIN "gfx/icons/vulpix.2bpp"
INCBIN "gfx/icons/ninetales.2bpp"
INCBIN "gfx/icons/jigglypuff.2bpp"
INCBIN "gfx/icons/wigglytuff.2bpp"
INCBIN "gfx/icons/zubat.2bpp"
INCBIN "gfx/icons/golbat.2bpp"
INCBIN "gfx/icons/oddish.2bpp"
INCBIN "gfx/icons/gloom.2bpp"
INCBIN "gfx/icons/vileplume.2bpp"
INCBIN "gfx/icons/paras.2bpp"
INCBIN "gfx/icons/parasect.2bpp"
INCBIN "gfx/icons/venonat.2bpp"
INCBIN "gfx/icons/venomoth.2bpp"
INCBIN "gfx/icons/diglett.2bpp"
INCBIN "gfx/icons/dugtrio.2bpp"
INCBIN "gfx/icons/meowth.2bpp"
INCBIN "gfx/icons/persian.2bpp"
INCBIN "gfx/icons/psyduck.2bpp"
INCBIN "gfx/icons/golduck.2bpp"
INCBIN "gfx/icons/mankey.2bpp"
INCBIN "gfx/icons/primeape.2bpp"
INCBIN "gfx/icons/growlithe.2bpp"
INCBIN "gfx/icons/arcanine.2bpp"
INCBIN "gfx/icons/poliwag.2bpp"
INCBIN "gfx/icons/poliwhirl.2bpp"
INCBIN "gfx/icons/poliwrath.2bpp"
INCBIN "gfx/icons/abra.2bpp"
INCBIN "gfx/icons/kadabra.2bpp"
INCBIN "gfx/icons/alakazam.2bpp"
INCBIN "gfx/icons/machop.2bpp"
INCBIN "gfx/icons/machoke.2bpp"
INCBIN "gfx/icons/machamp.2bpp"
INCBIN "gfx/icons/bellsprout.2bpp"
INCBIN "gfx/icons/weepinbell.2bpp"
INCBIN "gfx/icons/victreebel.2bpp"
INCBIN "gfx/icons/tentacool.2bpp"
INCBIN "gfx/icons/tentacruel.2bpp"
INCBIN "gfx/icons/geodude.2bpp"
INCBIN "gfx/icons/graveler.2bpp"
INCBIN "gfx/icons/golem.2bpp"
INCBIN "gfx/icons/ponyta.2bpp"
INCBIN "gfx/icons/rapidash.2bpp"
INCBIN "gfx/icons/slowpoke.2bpp"
INCBIN "gfx/icons/slowbro.2bpp"
INCBIN "gfx/icons/magnemite.2bpp"
INCBIN "gfx/icons/magneton.2bpp"
INCBIN "gfx/icons/farfetchd.2bpp"
INCBIN "gfx/icons/doduo.2bpp"
INCBIN "gfx/icons/dodrio.2bpp"
INCBIN "gfx/icons/seel.2bpp"
INCBIN "gfx/icons/dewgong.2bpp"
INCBIN "gfx/icons/grimer.2bpp"
INCBIN "gfx/icons/muk.2bpp"
INCBIN "gfx/icons/shellder.2bpp"
INCBIN "gfx/icons/cloyster.2bpp"
INCBIN "gfx/icons/gastly.2bpp"
INCBIN "gfx/icons/haunter.2bpp"
INCBIN "gfx/icons/gengar.2bpp"
INCBIN "gfx/icons/onix.2bpp"
INCBIN "gfx/icons/drowzee.2bpp"
INCBIN "gfx/icons/hypno.2bpp"
INCBIN "gfx/icons/krabby.2bpp"
INCBIN "gfx/icons/kingler.2bpp"
INCBIN "gfx/icons/voltorb.2bpp"
INCBIN "gfx/icons/electrode.2bpp"
INCBIN "gfx/icons/exeggcute.2bpp"
INCBIN "gfx/icons/exeggutor.2bpp"
INCBIN "gfx/icons/cubone.2bpp"
INCBIN "gfx/icons/marowak.2bpp"
INCBIN "gfx/icons/hitmonlee.2bpp"
INCBIN "gfx/icons/hitmonchan.2bpp"
INCBIN "gfx/icons/lickitung.2bpp"
INCBIN "gfx/icons/koffing.2bpp"
INCBIN "gfx/icons/weezing.2bpp"
INCBIN "gfx/icons/rhyhorn.2bpp"
INCBIN "gfx/icons/rhydon.2bpp"
INCBIN "gfx/icons/chansey.2bpp"
INCBIN "gfx/icons/tangela.2bpp"
INCBIN "gfx/icons/kangaskhan.2bpp"
INCBIN "gfx/icons/horsea.2bpp"
INCBIN "gfx/icons/seadra.2bpp"
INCBIN "gfx/icons/goldeen.2bpp"
INCBIN "gfx/icons/seaking.2bpp"
INCBIN "gfx/icons/staryu.2bpp"
INCBIN "gfx/icons/starmie.2bpp"
INCBIN "gfx/icons/mr.mime.2bpp"
INCBIN "gfx/icons/scyther.2bpp"
INCBIN "gfx/icons/jynx.2bpp"
INCBIN "gfx/icons/electabuzz.2bpp"
INCBIN "gfx/icons/magmar.2bpp"
INCBIN "gfx/icons/pinsir.2bpp"


SECTION "Icons Rapaz2", ROMX

INCBIN "gfx/icons/tauros.2bpp"
INCBIN "gfx/icons/magikarp.2bpp"
INCBIN "gfx/icons/gyarados.2bpp"
INCBIN "gfx/icons/lapras.2bpp"
INCBIN "gfx/icons/ditto.2bpp"
INCBIN "gfx/icons/eevee.2bpp"
INCBIN "gfx/icons/vaporeon.2bpp"
INCBIN "gfx/icons/jolteon.2bpp"
INCBIN "gfx/icons/flareon.2bpp"
INCBIN "gfx/icons/porygon.2bpp"
INCBIN "gfx/icons/omanyte.2bpp"
INCBIN "gfx/icons/omastar.2bpp"
INCBIN "gfx/icons/kabuto.2bpp"
INCBIN "gfx/icons/kabutops.2bpp"
INCBIN "gfx/icons/aerodactyl.2bpp"
INCBIN "gfx/icons/snorlax.2bpp"
INCBIN "gfx/icons/articuno.2bpp"
INCBIN "gfx/icons/zapdos.2bpp"
INCBIN "gfx/icons/moltres.2bpp"
INCBIN "gfx/icons/dratini.2bpp"
INCBIN "gfx/icons/dragonair.2bpp"
INCBIN "gfx/icons/dragonite.2bpp"
INCBIN "gfx/icons/mewtwo.2bpp"
INCBIN "gfx/icons/mew.2bpp"
INCBIN "gfx/icons/leafeon.2bpp"
INCBIN "gfx/icons/chikorita.2bpp"
INCBIN "gfx/icons/bayleef.2bpp"
INCBIN "gfx/icons/meganium.2bpp"
INCBIN "gfx/icons/hoothoot.2bpp"
INCBIN "gfx/icons/noctowl.2bpp"
INCBIN "gfx/icons/ledyba.2bpp"
INCBIN "gfx/icons/ledian.2bpp"
INCBIN "gfx/icons/spinarak.2bpp"
INCBIN "gfx/icons/ariados.2bpp"
INCBIN "gfx/icons/crobat.2bpp"
INCBIN "gfx/icons/togepi.2bpp"
INCBIN "gfx/icons/natu.2bpp"
INCBIN "gfx/icons/xatu.2bpp"
INCBIN "gfx/icons/mareep.2bpp"
INCBIN "gfx/icons/flaaffy.2bpp"
INCBIN "gfx/icons/ampharos.2bpp"
INCBIN "gfx/icons/bellossom.2bpp"
INCBIN "gfx/icons/marill.2bpp"
INCBIN "gfx/icons/azumarill.2bpp"
INCBIN "gfx/icons/aipom.2bpp"
INCBIN "gfx/icons/sunflora.2bpp"
INCBIN "gfx/icons/espeon.2bpp"
INCBIN "gfx/icons/umbreon.2bpp"
INCBIN "gfx/icons/slowking.2bpp"
INCBIN "gfx/icons/steelix.2bpp"
INCBIN "gfx/icons/snubbull.2bpp"
INCBIN "gfx/icons/qwilfish.2bpp"
INCBIN "gfx/icons/scizor.2bpp"
INCBIN "gfx/icons/remoraid.2bpp"
INCBIN "gfx/icons/octillery.2bpp"
INCBIN "gfx/icons/skarmory.2bpp"
INCBIN "gfx/icons/houndour.2bpp"
INCBIN "gfx/icons/houndoom.2bpp"
INCBIN "gfx/icons/phanpy.2bpp"
INCBIN "gfx/icons/donphan.2bpp"
INCBIN "gfx/icons/smeargle.2bpp"
INCBIN "gfx/icons/miltank.2bpp"
INCBIN "gfx/icons/hooh.2bpp"
INCBIN "gfx/icons/chinchou.2bpp"
INCBIN "gfx/icons/cyndaquil.2bpp"
INCBIN "gfx/icons/quilava.2bpp"
INCBIN "gfx/icons/typhlosion.2bpp"
INCBIN "gfx/icons/totodile.2bpp"
INCBIN "gfx/icons/croconaw.2bpp"
INCBIN "gfx/icons/feraligatr.2bpp"
INCBIN "gfx/icons/sentret.2bpp"
INCBIN "gfx/icons/furret.2bpp"
INCBIN "gfx/icons/sudowoodo.2bpp"
